services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - AUTH_SERVICE=http://user-authentication:5002/api/auth
      - ANALYTICS_SERVICE=http://recipe-analytics:5003/api/analytics
      - RECIPE_SERVICE=http://recipe-vault:5004/api/recipes
      - USER_SERVICE=http://user-management:5001/api/user
    depends_on:
      - user-authentication
      - recipe-analytics
      - recipe-vault
      - user-management

  user-authentication:
    build:
      context: .
      dockerfile: user-authentication/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - PORT=5002

  user-management:
    build:
      context: .
      dockerfile: user-management/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001

  recipe-analytics:
    build:
      context: .
      dockerfile: recipe-analytics/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - PORT=5003

  recipe-vault:
    build:
      context: .
      dockerfile: recipe-vault/Dockerfile
    ports:
      - "5004:5004"
    environment:
      - PORT=5004