name: CI/CD Pipeline for Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Define Heroku app names
  HEROKU_API_GATEWAY: cook-assist-api
  HEROKU_USER_AUTH: cook-assist-auth
  HEROKU_USER_MANAGEMENT: cook-assist-user
  HEROKU_RECIPE_ANALYTICS: cook-assist-analytics
  HEROKU_RECIPE_VAULT: cook-assist-vault
  HEROKU_FRONTEND: cook-assist-front

jobs:
  build:
    name: Build and Push Docker Images to Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

      # Function to build, push, and verify images
      - name: Build and Push Services
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          services=(
            "api-gateway ${{ env.HEROKU_API_GATEWAY }}"
            "user-authentication ${{ env.HEROKU_USER_AUTH }}"
            "user-management ${{ env.HEROKU_USER_MANAGEMENT }}"
            "recipe-analytics ${{ env.HEROKU_RECIPE_ANALYTICS }}"
            "recipe-vault ${{ env.HEROKU_RECIPE_VAULT }}"
          )

          for service in "${services[@]}"; do
            IFS=" " read -r dir app <<< "$service"
            echo "Building and pushing $dir to $app..."
            cd Backend/services/$dir
            heroku container:push web -a $app
            heroku container:info web -a $app
            cd - # Return to previous directory
          done

          # Frontend
          echo "Building and pushing frontend..."
          cd Frontend
          heroku container:push web -a ${{ env.HEROKU_FRONTEND }}
          heroku container:info web -a ${{ env.HEROKU_FRONTEND }}

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

      - name: Release Services
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          services=(
            "${{ env.HEROKU_API_GATEWAY }}"
            "${{ env.HEROKU_USER_AUTH }}"
            "${{ env.HEROKU_USER_MANAGEMENT }}"
            "${{ env.HEROKU_RECIPE_ANALYTICS }}"
            "${{ env.HEROKU_RECIPE_VAULT }}"
            "${{ env.HEROKU_FRONTEND }}"
          )

          for app in "${services[@]}"; do
            echo "Releasing $app..."
            heroku container:release web -a $app
          done
