name: CI/CD Pipeline for Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Define your Heroku app names
  HEROKU_API_GATEWAY: cook-assist-api
  HEROKU_USER_AUTH: cook-assist-auth
  HEROKU_USER_MANAGEMENT: cook-assist-user
  HEROKU_RECIPE_ANALYTICS: cook-assist-analytics
  HEROKU_RECIPE_VAULT: cook-assist-vault
  HEROKU_FRONTEND: cook-assist-front

jobs:
  build_and_deploy:
    name: Build, Push, and Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install the Heroku CLI (required for heroku container:* commands)
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Login to Heroku Container Registry using API Key
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
          echo "Logged in successfully to Heroku Container Registry."

      # Build, Push, and Deploy API Gateway
      - name: Build, Push, and Deploy API Gateway
        run: |
          echo "Building, pushing, and deploying API Gateway..."
          cd Backend/services/api-gateway
          heroku container:push web -a ${{ env.HEROKU_API_GATEWAY }}
          heroku container:release web -a ${{ env.HEROKU_API_GATEWAY }}
          cd - # Return to the previous directory

      # Build, Push, and Deploy User Authentication
      - name: Build, Push, and Deploy User Authentication
        run: |
          echo "Building, pushing, and deploying User Authentication..."
          cd Backend/services/user-authentication
          heroku container:push web -a ${{ env.HEROKU_USER_AUTH }}
          heroku container:release web -a ${{ env.HEROKU_USER_AUTH }}
          cd - # Return to the previous directory

      # Build, Push, and Deploy User Management
      - name: Build, Push, and Deploy User Management
        run: |
          echo "Building, pushing, and deploying User Management..."
          cd Backend/services/user-management
          heroku container:push web -a ${{ env.HEROKU_USER_MANAGEMENT }}
          heroku container:release web -a ${{ env.HEROKU_USER_MANAGEMENT }}
          cd - # Return to the previous directory

      # Build, Push, and Deploy Recipe Analytics
      - name: Build, Push, and Deploy Recipe Analytics
        run: |
          echo "Building, pushing, and deploying Recipe Analytics..."
          cd Backend/services/recipe-analytics
          heroku container:push web -a ${{ env.HEROKU_RECIPE_ANALYTICS }}
          heroku container:release web -a ${{ env.HEROKU_RECIPE_ANALYTICS }}
          cd - # Return to the previous directory

      # Build, Push, and Deploy Recipe Vault
      - name: Build, Push, and Deploy Recipe Vault
        run: |
          echo "Building, pushing, and deploying Recipe Vault..."
          cd Backend/services/recipe-vault
          heroku container:push web -a ${{ env.HEROKU_RECIPE_VAULT }}
          heroku container:release web -a ${{ env.HEROKU_RECIPE_VAULT }}
          cd - # Return to the previous directory

      # Build, Push, and Deploy Frontend
      - name: Build, Push, and Deploy Frontend
        run: |
          echo "Building, pushing, and deploying Frontend..."
          cd Frontend
          heroku container:push web -a ${{ env.HEROKU_FRONTEND }}
          heroku container:release web -a ${{ env.HEROKU_FRONTEND }}
          cd - # Return to the previous directory
