name: CI/CD Pipeline for Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Define your Heroku app names
  HEROKU_API_GATEWAY: cook-assist-api
  HEROKU_USER_AUTH: cook-assist-auth
  HEROKU_USER_MANAGEMENT: cook-assist-user
  HEROKU_RECIPE_ANALYTICS: cook-assist-analytics
  HEROKU_RECIPE_VAULT: cook-assist-vault
  HEROKU_FRONTEND: cook-assist-front

jobs:
  build:
    name: Build and Push Docker Images to Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install the Heroku CLI (required for heroku container:* commands)
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Login to Heroku Container Registry using API Key
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

      # Build and push API Gateway
      - name: Build and Push API Gateway to Heroku
        run: |
          echo "Building and pushing API Gateway..."
          cd Backend/services/api-gateway
          heroku container:push web -a ${{ env.HEROKU_API_GATEWAY }}
          heroku container:release web -a ${{ env.HEROKU_API_GATEWAY }}
          cd - # Return to the previous directory

      # Build and push User Authentication
      - name: Build and Push User Authentication to Heroku
        run: |
          echo "Building and pushing User Authentication..."
          cd Backend/services/user-authentication
          heroku container:push web -a ${{ env.HEROKU_USER_AUTH }}
          heroku container:release web -a ${{ env.HEROKU_USER_AUTH }}
          cd - # Return to the previous directory

      # Build and push User Management
      - name: Build and Push User Management to Heroku
        run: |
          echo "Building and pushing User Management..."
          cd Backend/services/user-management
          heroku container:push web -a ${{ env.HEROKU_USER_MANAGEMENT }}
          heroku container:release web -a ${{ env.HEROKU_USER_MANAGEMENT }}
          cd - # Return to the previous directory

      # Build and push Recipe Analytics
      - name: Build and Push Recipe Analytics to Heroku
        run: |
          echo "Building and pushing Recipe Analytics..."
          cd Backend/services/recipe-analytics
          heroku container:push web -a ${{ env.HEROKU_RECIPE_ANALYTICS }}
          heroku container:release web -a ${{ env.HEROKU_RECIPE_ANALYTICS }}
          cd - # Return to the previous directory

      # Build and push Recipe Vault
      - name: Build and Push Recipe Vault to Heroku
        run: |
          echo "Building and pushing Recipe Vault..."
          cd Backend/services/recipe-vault
          heroku container:push web -a ${{ env.HEROKU_RECIPE_VAULT }}
          heroku container:release web -a ${{ env.HEROKU_RECIPE_VAULT }}
          cd - # Return to the previous directory

      # Build and push Frontend
      - name: Build and Push Frontend to Heroku
        run: |
          echo "Building and pushing Frontend..."
          cd Frontend
          heroku container:push web -a ${{ env.HEROKU_FRONTEND }}
          heroku container:release web -a ${{ env.HEROKU_FRONTEND }}
          cd - # Return to the previous directory

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | heroku auth:token

      - name: Release API Gateway on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ env.HEROKU_API_GATEWAY }}
        run: heroku container:release web -a $HEROKU_APP_NAME

      - name: Release User Authentication on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ env.HEROKU_USER_AUTH }}
        run: heroku container:release web -a $HEROKU_APP_NAME

      - name: Release User Management on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ env.HEROKU_USER_MANAGEMENT }}
        run: heroku container:release web -a $HEROKU_APP_NAME

      - name: Release Recipe Analytics on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ env.HEROKU_RECIPE_ANALYTICS }}
        run: heroku container:release web -a $HEROKU_APP_NAME

      - name: Release Recipe Vault on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ env.HEROKU_RECIPE_VAULT }}
        run: heroku container:release web -a $HEROKU_APP_NAME

      - name: Release Frontend on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ env.HEROKU_FRONTEND }}
        run: heroku container:release web -a $HEROKU_APP_NAME
